version: "3.8"

services:

  warblerdb:
    container_name: warblerdb
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./warbler.sql:/docker-entrypoint-initdb.d/warbler.sql

  warblerapp:
    container_name: warblerapp
    build: .
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@warblerdb:5432/postgres
      - SECRET_KEY=secret-key
    depends_on:
      - warblerdb

volumes:
  pgdata: {}

# optional: not required for single container stack
# networks:
#   default:
#     name: warbler-network


# to start containerized application, run:
# $ docker-compose up -d
